"""id_domaine is now not nullable

Revision ID: 0a0c33236d36
Revises: 59ae8e8d9ba2
Create Date: 2026-08-24 11:59:42.970775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0c33236d36'
down_revision: Union[str, Sequence[str], None] = '59ae8e8d9ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skill', 'id_domaine',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skill', 'id_domaine',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
