"""name_skill is now not nullable

Revision ID: 59ae8e8d9ba2
Revises: d32535c9a5d1
Create Date: 2026-08-24 11:57:44.557792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ae8e8d9ba2'
down_revision: Union[str, Sequence[str], None] = 'd32535c9a5d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skill', 'name_skill',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_check_constraint('chk_training_only_one_main_target', 'training', 'NOT (id_certification IS NOT NULL AND id_diploma IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_training_only_one_main_target', 'training', type_='check')
    op.alter_column('skill', 'name_skill',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
