"""add soft delete to access level

Revision ID: a911db9d2ce2
Revises: 0a0c33236d36
Create Date: 2026-09-25 14:42:42.284650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a911db9d2ce2'
down_revision: Union[str, Sequence[str], None] = '0a0c33236d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_level', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('domaine', 'nom_domaine',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('employee', 'hash_password',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('training_source', 'name_source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('trainingxskill', 'granted_level',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainingxskill', 'granted_level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('training_source', 'name_source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('employee', 'hash_password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('domaine', 'nom_domaine',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('access_level', 'is_deleted')
    # ### end Alembic commands ###
