-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.access_level
(
    id_access_level serial NOT NULL,
    label character varying(50) COLLATE pg_catalog."default" NOT NULL,
    level integer NOT NULL,
    CONSTRAINT access_level_pkey PRIMARY KEY (id_access_level)
);

CREATE TABLE IF NOT EXISTS public.alembic_version
(
    version_num character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

CREATE TABLE IF NOT EXISTS public.certification
(
    id_certification serial NOT NULL,
    subject_certification character varying(50) COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    id_domaine integer NOT NULL,
    validity_month integer,
    CONSTRAINT certification_pkey PRIMARY KEY (id_certification)
);

CREATE TABLE IF NOT EXISTS public.certificationxskill
(
    id_certification integer NOT NULL,
    id_skill integer NOT NULL,
    granted_level integer,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT certificationxskill_pkey PRIMARY KEY (id_certification, id_skill)
);

CREATE TABLE IF NOT EXISTS public.diploma
(
    id_diploma serial NOT NULL,
    subject_diploma character varying(50) COLLATE pg_catalog."default",
    level_diploma character varying(50) COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    id_domaine integer NOT NULL,
    CONSTRAINT diploma_pkey PRIMARY KEY (id_diploma)
);

CREATE TABLE IF NOT EXISTS public.diplomaxskill
(
    id_diploma integer NOT NULL,
    id_skill integer NOT NULL,
    min_level integer,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT diplomaxskill_pkey PRIMARY KEY (id_diploma, id_skill)
);

CREATE TABLE IF NOT EXISTS public.domaine
(
    id_domaine serial NOT NULL,
    nom_domaine character varying(50) COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT domaine_pkey PRIMARY KEY (id_domaine)
);

CREATE TABLE IF NOT EXISTS public.employee
(
    id_employee serial NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default",
    last_name character varying(50) COLLATE pg_catalog."default",
    hash_password character varying(255) COLLATE pg_catalog."default",
    mail character varying(50) COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    id_role integer NOT NULL,
    id_manager integer,
    CONSTRAINT employee_pkey PRIMARY KEY (id_employee)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_employee_mail_active
    ON public.employee (mail)
    WHERE is_deleted = false;

CREATE TABLE IF NOT EXISTS public.employeexcertification
(
    id_employee_certification serial NOT NULL,
    id_employee integer NOT NULL,
    id_certification integer NOT NULL,
    start_ date,
    end_ date,
    expiration date,
    organism character varying(50) COLLATE pg_catalog."default",
    evaluation character varying(50) COLLATE pg_catalog."default",
    doc character varying(255) COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT employeexcertification_pkey PRIMARY KEY (id_employee_certification)
);

CREATE TABLE IF NOT EXISTS public.employeexdiploma
(
    id_employee integer NOT NULL,
    id_diploma integer NOT NULL,
    end_ date,
    school character varying(50) COLLATE pg_catalog."default",
    start_ date,
    distinction character varying(50) COLLATE pg_catalog."default",
    doc character varying(50) COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT employeexdiploma_pkey PRIMARY KEY (id_employee, id_diploma)
);

CREATE TABLE IF NOT EXISTS public.participation
(
    id_employee integer NOT NULL,
    id_training integer NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT participation_pkey PRIMARY KEY (id_employee, id_training)
);

CREATE TABLE IF NOT EXISTS public.participation_document
(
    id_participation_document serial NOT NULL,
    id_employee integer NOT NULL,
    id_training integer NOT NULL,
    document_type character varying(40) NOT NULL,
    original_filename character varying(255) NOT NULL,
    storage_key character varying(255) NOT NULL UNIQUE,
    mime_type character varying(100) NOT NULL,
    size_bytes integer NOT NULL,
    uploaded_at timestamp with time zone NOT NULL,
    id_uploaded_by integer NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT participation_document_pkey PRIMARY KEY (id_participation_document),
    CONSTRAINT participation_document_participation_fkey FOREIGN KEY (id_employee, id_training)
        REFERENCES public.participation (id_employee, id_training),
    CONSTRAINT participation_document_uploader_fkey FOREIGN KEY (id_uploaded_by)
        REFERENCES public.employee (id_employee)
);

CREATE TABLE IF NOT EXISTS public.provide
(
    id_training integer NOT NULL,
    id_source integer NOT NULL,
    cost_hour numeric(15, 2),
    duration_hours numeric(15, 2),
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT provide_pkey PRIMARY KEY (id_training, id_source)
);

CREATE TABLE IF NOT EXISTS public.role
(
    id_role serial NOT NULL,
    denomination_role character varying(50) COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    id_access_level integer NOT NULL DEFAULT 1,
    CONSTRAINT role_pkey PRIMARY KEY (id_role)
);

CREATE TABLE IF NOT EXISTS public.skill
(
    id_skill serial NOT NULL,
    name_skill character varying(50) COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    id_domaine integer,
    CONSTRAINT skill_pkey PRIMARY KEY (id_skill)
);

CREATE TABLE IF NOT EXISTS public.skill_validation
(
    id_skill_validation serial NOT NULL,
    date_ date,
    validated_at timestamp with time zone,
    superseded_at timestamp with time zone,
    justification character varying(1000),
    level_skill integer,
    id_validation integer NOT NULL,
    id_employee integer NOT NULL,
    id_validator integer NOT NULL,
    id_skill integer NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT skill_validation_pkey PRIMARY KEY (id_skill_validation)
);

CREATE TABLE IF NOT EXISTS public.training
(
    id_training serial NOT NULL,
    title character varying(50) COLLATE pg_catalog."default",
    id_domaine integer,
    location character varying(255),
    start_ date,
    end_ date,
    is_deleted boolean NOT NULL DEFAULT false,
    id_certification integer,
    id_diploma integer,
    CONSTRAINT training_pkey PRIMARY KEY (id_training)
);

CREATE TABLE IF NOT EXISTS public.training_request
(
    id_training_request serial NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    reason character varying(500) COLLATE pg_catalog."default",
    requested_at date NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    id_employee integer NOT NULL,
    id_training integer,
    id_validator integer,
    request_desc character varying(150) COLLATE pg_catalog."default",
    CONSTRAINT training_request_pkey PRIMARY KEY (id_training_request)
);

CREATE TABLE IF NOT EXISTS public.training_source
(
    id_source serial NOT NULL,
    name_source character varying(50) COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT training_source_pkey PRIMARY KEY (id_source)
);

CREATE TABLE IF NOT EXISTS public.trainingxskill
(
    id_skill integer NOT NULL,
    id_training integer NOT NULL,
    granted_level integer,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT trainingxskill_pkey PRIMARY KEY (id_skill, id_training)
);

CREATE TABLE IF NOT EXISTS public.validation_type
(
    id_validation serial NOT NULL,
    source character varying(50) COLLATE pg_catalog."default",
    denomination_validation character varying(50) COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT validation_type_pkey PRIMARY KEY (id_validation)
);

ALTER TABLE IF EXISTS public.certification
    ADD CONSTRAINT certification_id_domaine_fkey FOREIGN KEY (id_domaine)
    REFERENCES public.domaine (id_domaine) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.certificationxskill
    ADD CONSTRAINT certificationxskill_id_certification_fkey FOREIGN KEY (id_certification)
    REFERENCES public.certification (id_certification) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.certificationxskill
    ADD CONSTRAINT certificationxskill_id_skill_fkey FOREIGN KEY (id_skill)
    REFERENCES public.skill (id_skill) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.diploma
    ADD CONSTRAINT diploma_id_domaine_fkey FOREIGN KEY (id_domaine)
    REFERENCES public.domaine (id_domaine) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.diplomaxskill
    ADD CONSTRAINT diplomaxskill_id_diploma_fkey FOREIGN KEY (id_diploma)
    REFERENCES public.diploma (id_diploma) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.diplomaxskill
    ADD CONSTRAINT diplomaxskill_id_skill_fkey FOREIGN KEY (id_skill)
    REFERENCES public.skill (id_skill) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employee
    ADD CONSTRAINT employee_id_manager_fkey FOREIGN KEY (id_manager)
    REFERENCES public.employee (id_employee) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employee
    ADD CONSTRAINT employee_id_role_fkey FOREIGN KEY (id_role)
    REFERENCES public.role (id_role) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employeexcertification
    ADD CONSTRAINT employeexcertification_id_certification_fkey FOREIGN KEY (id_certification)
    REFERENCES public.certification (id_certification) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employeexcertification
    ADD CONSTRAINT employeexcertification_id_employee_fkey FOREIGN KEY (id_employee)
    REFERENCES public.employee (id_employee) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employeexdiploma
    ADD CONSTRAINT employeexdiploma_id_diploma_fkey FOREIGN KEY (id_diploma)
    REFERENCES public.diploma (id_diploma) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employeexdiploma
    ADD CONSTRAINT employeexdiploma_id_employee_fkey FOREIGN KEY (id_employee)
    REFERENCES public.employee (id_employee) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.participation
    ADD CONSTRAINT participation_id_employee_fkey FOREIGN KEY (id_employee)
    REFERENCES public.employee (id_employee) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.participation
    ADD CONSTRAINT participation_id_training_fkey FOREIGN KEY (id_training)
    REFERENCES public.training (id_training) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.provide
    ADD CONSTRAINT provide_id_source_fkey FOREIGN KEY (id_source)
    REFERENCES public.training_source (id_source) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.provide
    ADD CONSTRAINT provide_id_training_fkey FOREIGN KEY (id_training)
    REFERENCES public.training (id_training) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.role
    ADD CONSTRAINT role_id_access_level_fkey FOREIGN KEY (id_access_level)
    REFERENCES public.access_level (id_access_level) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.skill
    ADD CONSTRAINT skill_id_domaine_fkey FOREIGN KEY (id_domaine)
    REFERENCES public.domaine (id_domaine) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.skill_validation
    ADD CONSTRAINT skill_validation_id_employee_fkey FOREIGN KEY (id_employee)
    REFERENCES public.employee (id_employee) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.skill_validation
    ADD CONSTRAINT skill_validation_id_skill_fkey FOREIGN KEY (id_skill)
    REFERENCES public.skill (id_skill) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.skill_validation
    ADD CONSTRAINT skill_validation_id_validation_fkey FOREIGN KEY (id_validation)
    REFERENCES public.validation_type (id_validation) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.skill_validation
    ADD CONSTRAINT skill_validation_id_validator_fkey FOREIGN KEY (id_validator)
    REFERENCES public.employee (id_employee) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.training
    ADD CONSTRAINT training_id_certification_fkey FOREIGN KEY (id_certification)
    REFERENCES public.certification (id_certification) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.training
    ADD CONSTRAINT training_id_diploma_fkey FOREIGN KEY (id_diploma)
    REFERENCES public.diploma (id_diploma) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.training
    ADD CONSTRAINT training_id_domaine_fkey FOREIGN KEY (id_domaine)
    REFERENCES public.domaine (id_domaine) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.training_request
    ADD CONSTRAINT training_request_id_employee_fkey FOREIGN KEY (id_employee)
    REFERENCES public.employee (id_employee) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.training_request
    ADD CONSTRAINT training_request_id_training_fkey FOREIGN KEY (id_training)
    REFERENCES public.training (id_training) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.training_request
    ADD CONSTRAINT training_request_id_validator_fkey FOREIGN KEY (id_validator)
    REFERENCES public.employee (id_employee) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.trainingxskill
    ADD CONSTRAINT trainingxskill_id_skill_fkey FOREIGN KEY (id_skill)
    REFERENCES public.skill (id_skill) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.trainingxskill
    ADD CONSTRAINT trainingxskill_id_training_fkey FOREIGN KEY (id_training)
    REFERENCES public.training (id_training) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;
